#include "\a3\ui_f\hpp\defineCommonGrids.inc"

#define POS_X(N) ((N) * GUI_GRID_W + GUI_GRID_CENTER_X)
#define POS_Y(N) ((N) * GUI_GRID_H + GUI_GRID_CENTER_Y)
#define POS_W(N) ((N) * GUI_GRID_W)
#define POS_H(N) ((N) * GUI_GRID_H)

#define SPACING 0.01
#define DIALOG_WIDTH POS_W(44)
#define DIALOG_HEIGHT POS_H(25)
#define DIALOG_TITLE_HEIGHT POS_H(1.2)
#define BUTTON_HEIGHT 0.022 * safeZoneH

#define STARTING_POS_X POS_X(-2)
#define STARTING_POS_Y POS_Y(0.5)
#define END_POS_X (STARTING_POS_X + DIALOG_WIDTH)
#define STARTING_POS_BUTTON (STARTING_POS_Y + DIALOG_HEIGHT + SPACING)

#define LIST_WIDTH (DIALOG_WIDTH / 3)

#define GRID_POS_X(GRIDCOL, GRID) (STARTING_POS_X + ((DIALOG_WIDTH / GRID) * (GRIDCOL - 1)))
#define GRID_POS_Y(GRIDROW, GRID, HVAL) (((STARTING_POS_Y + DIALOG_HEIGHT) / GRID) * (GRIDROW - 1)) + HVAL + SPACING

#define IDD_ITEM_RANKS_DIALOG 12094812
#define IDC_ITEMS_LISTBOX 1500
#define IDC_RANKS_LISTBOX 1501
#define IDC_ITEMS_COMBO 2100
#define IDC_RANKS_COMBO 2101
#define IDC_SAVE_BUTTON 2500
#define IDC_CANCEL_BUTTON 2502